version: '3.7'

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7.7-1
    networks:
      - red_guay_overlay
    ports:
      - "80:80"
    environment:
      - PMA_HOSTS=database
    volumes:
      - "database_viewer_volume:/etc/phpmyadmin/config.user.inc.php"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.region == database_view
      labels:
        - "DATABASE_VIEWER_ENV=PRE_PRODUCCION"
      restart_policy:
        condition: any
  
  database:
    ports:
      - "3306:3306"
    volumes:
      - "database_volume:/var/lib/mysql"
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=viewnext_docker
    networks:
      - red_guay_overlay
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.region == database
      labels:
        - "DATABASE_ENV=PRE_PRODUCCION"
      restart_policy:
        condition: any

volumes:
  database_volume:
    external: true
    name: database_volume

  database_viewer_volume:
    external: true
    name: database_viewer_volume

networks:
  red_guay_overlay:
    name: red_guay_overlay
    driver: overlay